# Generated by Django 3.2.8 on 2021-10-18 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
